apiVersion: v1
kind: configMap
metadata:
 name: payment
 namespace: roboshop
type: Opaque
data:
       CART_HOST: "cart"
       CART_PORT: "8080"
       USER_HOST: "user"
       USER_PORT: "8080"
       AMQP_HOST: "rabbitmq"
       AMQP_USER: "roboshop"

---
apiVersion: v1
kind: Secret
metadata:
 name: payment
 namespace: roboshop
type: Opaque
data:
  AMQP_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: payment
 namespace: roboshop
 labels:
  project: roboshop
  environment: dev
  tier: backend
spec:
 replicas: 1
 selectors:
  matchLabels:
    project: roboshop
    environment: dev
    tier: backend
 template:
  metadata:
   name: payment
  spec:
   containers:
    - name: payment
      image: harshatejaadduri/payment:v2
      envFrom:
       - configMapRef: 
         name: payment
       - secretRef:
         name: payment

---
apiVersion: apps/v1
kind: Service
metadata: 
 name: payment
 namespace: roboshop
 labels:
  project: roboshop
  environment: dev
  tier: backend         
spec:
 selector:
  project: roboshop
  environment: dev
  tier: backend  
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
