apiVersion: v1 
kind: configMap
metadata: 
  name: cart
  namespace: roboshop
data:
 REDIS_HOST: "redis" 
 CATALOGUE_HOST: "catalogue" 
 CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: cart
 namespace: roboshop
 labels:
  project: roboshop
  tier: backend
  environment: dev
spec:
 replicas: 1
 selector:
  matchLabels: 
    project: roboshop
    tier: backend
    environment: dev
 template:
  metadata:
   name: cart
   namespace: roboshop
  spec: 
   containers:
    - name: cart
      image: harshatejaadduri/cart:v2
      envFrom:
       - configMapRef:
          name: cart 

---
apiVersion: v1 
kind: Service
metadata: 
  name: cart
  namespace: roboshop
spec:
 selector:
    project: roboshop
    tier: backend
    environment: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
 