apiVersion: v1 
kind: ConfigMap
metadata:
 name: shipping
 namespace: roboshop
 labels:
  project: roboshop
  environment: dev
  tier: backend
data:
 CART_ENDPOINT: "cart:8080" 
 DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: shipping
 namespace: roboshop
 labels:
  project: roboshop
  environment: dev
  tier: backend
spec:
 replicas: 1
 selector:
  matchLabels:
    project: roboshop
    environment: dev
    tier: backend
 template:
  metadata:
   name: shipping
   labels: 
    project: roboshop
    environment: dev
    tier: backend
  spec:
   containers:
    - name: shipping
      image: harshatejaadduri/shipping:v2
      envFrom:
       - configMapRef:
          name: shipping

---
apiVersion: v1 
kind: Service
metadata: 
 name: shipping
 namespace: roboshop
spec:
 selector:
  project: roboshop
  environment: dev
  tier: backend
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
          