apiVersion: v1
kind: Secret
metadata: 
 name: rabbitmq
 namespace: roboshop
type: Opaque
data:
   RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
   RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
  project: roboshop
  environment: dev
  tier: database
spec:
 replicas: 1
 selectors:
  matchLabels:
    project: roboshop
    environment: dev
    tier: database
 template: 
  metadata: 
   name: rabbitmq
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3 
      envFrom:
       - secretRef:
         name: rabbitmq 

---

apiVersion: v1
kind: Service
metadata: 
 name: rabbitmq
 namespace: roboshop
spec:
 selector:
  project: roboshop
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
