apiVersion: v1
kind: Secret
metadata:
 name: mysql 
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

type: Opaque
data:
 MYSQL_ROOT_PASS: "Um9ib1Nob3BAMQ=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database
spec:
 replicas: 1
 selector:
  matchLabels:
    component: mysql
    environment: dev
    tier: database
 template:
  metadata:
   labels:
     component: mysql
     environment: dev
     tier: database
  spec: 
   containers:
    - name: mysql
      image: harshatejaadduri/mysql:v2
      envFrom:
       - secretRef:
          name: mysql

---
apiVersion: v1 
kind: Service
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database
spec:
 selector:
  component: mysql
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
