apiVersion: v1 
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  project: roboshop
  tier: backend  
data:
  REDIS_URL: 'redis://redis:6379' 
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  project: roboshop
  tier: backend
spec:  
 replicas: 1
 selector:
  matchLabels:
    environment: dev
    project: roboshop
    tier: backend
 template:
  metadata:
   labels:
    environment: dev
    project: roboshop
    tier: backend   
  spec: 
   containers:
    - name: user
      image: harshatejaadduri/user:v2
      envFrom:
       - configMapRef:
          name: user

--- 
apiVersion: v1 
kind: Service
metadata:
 name: user
 namespace: roboshop
 labels:
    environment: dev
    project: roboshop
    tier: backend  
spec:
 selector:
    environment: dev
    project: roboshop
    tier: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
