apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis 
 namespace: roboshop
 labels:
  project: roboshop
  environment: dev
  tier: database
spec:
 replicas: 1
 selector:
  matchLabels:
    project: roboshop
    environment: dev
    tier: database
 template:
  metadata:
   name: redis
   labels:
    project: roboshop
    environment: dev
    tier: database    
  spec: 
   containers:
    - name: redis
      image: redis:7.0 

--- 
apiVersion: v1
kind: Service
metadata: 
 name: redis
 namespace: roboshop
spec:
 selector:
  project: roboshop
  environment: dev
  tier: database
 ports: 
  - protocol: TCP
    port: 6379
    targetPort: 6379